--Tạo Schema
alter session set "_ORACLE_SCRIPT"=true;
CREATE USER QLYPHONGGYM IDENTIFIED BY pass123;
GRANT CONNECT, RESOURCE, DBA TO QLYPHONGGYM;


--Sử dụng Schema
ALTER SESSION SET CURRENT_SCHEMA = QLYPHONGGYM;

--Tạo bảng CUSTOMER
CREATE TABLE CUSTOMER (
  MaKH VARCHAR2(10) PRIMARY KEY,
  HoTen VARCHAR2(50) NOT NULL,
  NgaySinh DATE ,
  GioiTinh VARCHAR2(10),
  Email  VARCHAR2(50) NOT NULL,
  SoDienThoai VARCHAR2(15) NOT NULL,
  DiaChi VARCHAR2(100),
  ReferralCode VARCHAR2(20) UNIQUE
);

--Tạo bảng PACKAGE
CREATE TABLE PACKAGE (
  MaGoi VARCHAR2(10) PRIMARY KEY,
  TenGoi  VARCHAR2(50) NOT NULL,
  LoaiGoi VARCHAR2(20) CHECK (LoaiGoi IN ('Cardio', 'Gym', 'Yoga', 'Combo')),
  GiaTien NUMBER(10,2) NOT NULL,
  ThoiHan NUMBER(3) NOT NULL
);

--Tạo bảng WORKOUT_AREA
CREATE TABLE WORKOUT_AREA (
  MaKhuVuc  VARCHAR2(10) PRIMARY KEY,
  TenKhuVuc VARCHAR2(50) NOT NULL,
  SucChuaToiDa NUMBER(3) NOT NULL
); 

--Tạo bảng SCHEDULE
CREATE TABLE SCHEDULE (
  MaLich  VARCHAR2(10) PRIMARY KEY,
  MaKH  VARCHAR2(10) NOT NULL, 
  MaGoi VARCHAR2(10) NOT NULL,
  NgayTap DATE NOT NULL,
  CaTap NUMBER(1) CHECK(CaTap BETWEEN 1 AND 5),
  PhongTap VARCHAR2(20) NOT NULL, 
  MaPT VARCHAR2(10) NOT NULL
);

--Tạo bảng PT
CREATE TABLE PT (
  MaPT  VARCHAR2(10) PRIMARY KEY,
  HoTenPT VARCHAR2(50) NOT NULL,
  ChuyenMon VARCHAR2(50),
  LichLamViec VARCHAR2(50),
  SoDienThoaiPT VARCHAR2(15) UNIQUE,
  EmailPT VARCHAR2(50) UNIQUE
);

--Tạo bảng STAFF
CREATE TABLE STAFF  (
  MaNV  VARCHAR2(10) PRIMARY KEY,
  HoTenNV VARCHAR2(50) NOT NULL,
  ViTri VARCHAR2(30) NOT NULL,
  LichLamViec VARCHAR2(50),
  SoDienThoaiNV VARCHAR2(15) UNIQUE, 
  EmailNV VARCHAR2(50) UNIQUE
);

--Tạo bảng PAYMENT
CREATE TABLE PAYMENT  (
  MaGD  VARCHAR2(15) PRIMARY KEY,
  MaKH  VARCHAR2(10) NOT NULL,
  SoTien  NUMBER(10,2) NOT NULL,
  PhuongThucTT VARCHAR2(20) CHECK(PhuongThucTT IN ('Tien Mat', 'The', 'Vi Dien Tu')),
  NgayTT DATE NOT NULL 
);

--Tạo bảng REWARD
CREATE TABLE REWARD (
  MaUuDai VARCHAR2(10)  PRIMARY KEY,
  MaKH  VARCHAR2(10)  NOT NULL,
  DiemTichLuy NUMBER(5) NOT NULL,
  MoTaUuDai VARCHAR2(100)
);

--Tạo bảng ATTENDANCE
CREATE TABLE ATTENDANCE (
  MaDiemDanh VARCHAR2(10) PRIMARY KEY,
  MaKH VARCHAR2(10) NOT NULL,
  NgayDiemDanh DATE NOT NULL,
  TrangThai VARCHAR2(20)  CHECK (TrangThai IN ('Đã điểm danh', 'Vắng mặt'))
);

--Tạo bảng EQUIPMENT
CREATE TABLE EQUIPMENT (
  MaTB  VARCHAR2(10) PRIMARY KEY,
  TenTB VARCHAR2(50) NOT NULL,
  TinhTrang VARCHAR2(20) CHECK (TinhTrang IN ('Tốt', 'Cần bảo trì', 'Hỏng')),
  MaKhuVuc  VARCHAR2(10)  NOT NULL
);

--Tạo bảng CLASS
CREATE TABLE CLASS (
  MaLop VARCHAR2(10) PRIMARY KEY,
  TenLop  VARCHAR2(50)  NOT NULL,
  MaPT  VARCHAR2(10)  NOT NULL,
  GioBatDau DATE NOT NULL,
  GioKetThuc DATE NOT NULL,
  SoLuongToiDa  NUMBER(3) NOT NULL
);

--Tạo bảng SERVICE
CREATE TABLE SERVICE (
  MaDV  VARCHAR2(10)  PRIMARY KEY,
  TenDV VARCHAR2(50)  NOT NULL,
  GiaDV NUMBER(10,2)  NOT NULL,
  MoTaDV  VARCHAR2(100)
);

--Tạo bảng SUBSCRIPTION
CREATE TABLE SUBSCRIPTION  (
  MaDK VARCHAR2(10) PRIMARY KEY,
  MaKH  VARCHAR2(10)  NOT NULL,
  MaDV  VARCHAR2(10)  NOT NULL,
  NgayDK  DATE  NOT NULL,
  TinhTrang VARCHAR2(20)  CHECK (TinhTrang IN ('Active', 'Expired'))
);

--Tạo bảng MEMBERSHIP
CREATE TABLE MEMBERSHIP (
  MaHV  VARCHAR2(10) PRIMARY KEY,
  MaKH  VARCHAR2(10) NOT NULL,
  LoaiHV  VARCHAR2(20)  CHECK (LoaiHV IN ('Silver', 'Gold', 'Platinum')),
  NgayBatDau  DATE NOT NULL,
  NgayKetThuc DATE 
);

--Tạo bảng DISCOUNT
CREATE TABLE DISCOUNT (
  MaGiamGia  VARCHAR2(10) PRIMARY KEY,
  TenMa  VARCHAR2(50) NOT NULL,
  PhanTram  NUMBER(3) CHECK (PhanTram BETWEEN 0 AND 100),
  HanSuDung DATE  NOT NULL,
  DieuKien  VARCHAR2(100)
);

--Tạo bảng BOOKING
CREATE TABLE BOOKING (
  MaBooking VARCHAR2(10) PRIMARY KEY,
  MaKH  VARCHAR2(10) NOT NULL,
  MaDV  VARCHAR2(10) NOT NULL,
  NgayDat DATE NOT NULL,
  TrangThai VARCHAR2(20)  CHECK (TrangThai IN ('Đã xác nhận', 'Chờ xử lý', 'Đã hủy'))
);

--Tạo bảng NOTIFICATION
CREATE TABLE  NOTIFICATION (
  MaTBao VARCHAR2(10) PRIMARY KEY,
  MaKH  VARCHAR2(10)  NOT NULL,
  TieuDe  VARCHAR2(50) NOT NULL,
  NoiDung VARCHAR2(255) NOT NULL,
  NgayGui DATE NOT NULL
);

--Tạo bảng FEEDBACK
CREATE TABLE FEEDBACK (
  MaFB VARCHAR2(10) PRIMARY KEY,
  MaKH VARCHAR2(10) NOT NULL,
  NoiDung VARCHAR2(255) NOT NULL,
  NgayGui DATE NOT NULL,
  DanhGia NUMBER(1) CHECK (DanhGia BETWEEN 1 AND 5)
);

--Tạo bảng MAINTENANCE
CREATE TABLE MAINTENANCE (
  MaBT  VARCHAR2(10)  PRIMARY KEY,
  MaTB  VARCHAR2(10)  NOT NULL,
  NgayBaoTri DATE NOT NULL,
  TrangThaiBT VARCHAR2(20)  CHECK (TrangThaiBT IN ('Đang xử lý', 'Hoàn thành')),
  MoTaBT  VARCHAR2(255)
);

--Tạo bảng PROMOTION
CREATE TABLE PROMOTION (
  MaKM  VARCHAR2(10)  PRIMARY KEY,
  TenKM VARCHAR2(50)  NOT NULL,
  MoTaKM  VARCHAR2(255), 
  NgayBatDau  DATE  NOT NULL,
  NgayKetThuc DATE  NOT NULL,
  PhanTramGiam  NUMBER(3) CHECK (PhanTramGiam BETWEEN 0 AND 100)
);

--Tạo bảng PT_ATTENDANCE
CREATE TABLE PT_ATTENDANCE (
  MaDDPT  VARCHAR2(10)  PRIMARY KEY,
  MaPT  VARCHAR2(10)  NOT NULL,
  NgayDiemDanh  DATE  NOT NULL,
  TrangThai VARCHAR2(20)  CHECK (TrangThai IN ('Có mặt', 'Vắng mặt', 'Nghỉ phép')),
  GhiChu  VARCHAR2(100)
);

--Tạo bảng STAFF_ATTENDANCE
CREATE TABLE STAFF_ATTENDANCE (
  MaDDNV VARCHAR2(10) PRIMARY KEY,
  MANV  VARCHAR2(10)  NOT NULL,
  NgayDiemDanh DATE NOT NULL,
  TrangThai VARCHAR2(20)  CHECK (TrangThai IN ('Có mặt', 'Vắng mặt', 'Nghỉ phép')),
  GhiChu  VARCHAR2(100)
);

--Tạo bảng CHALLENGE
CREATE TABLE CHALLENGE (
  MaChallenge VARCHAR2(10)  PRIMARY KEY,
  TenChallenge  VARCHAR2(50)  NOT NULL,
  MoTa  VARCHAR2(100) ,
  NgayBatDau  DATE  NOT NULL,
  NgayKetThuc DATE  NOT NULL,
  DiemThuong  NUMBER(5) NOT NULL
);

--Tạo bảng CHALLENGE_PARTICIPATION
CREATE TABLE CHALLENGE_PARTICIPATION (
  MaThamGia VARCHAR2(10) PRIMARY KEY,
  MaKH VARCHAR2(10) NOT NULL,
  MaChallenge VARCHAR2(10)  NOT NULL,
  TinhTrang VARCHAR2(20)  CHECK (TinhTrang IN ('Đang tham gia', 'Hoàn thành', 'Không hoàn thành')),
  NgayHoanThanh DATE
);

--Thêm thuộc tính

--  Bảng STAFF
ALTER TABLE STAFF
ADD Luong NUMBER(10,2) NOT NULL;
--  Bảng MAINTENANCE 
ALTER TABLE MAINTENANCE
ADD MaNV VARCHAR2(10);

--  Bảng SUBSCRIPTION
ALTER TABLE SUBSCRIPTION
ADD MaGoi VARCHAR2(10);

--  Bảng BOOKING
ALTER TABLE BOOKING
ADD MaGoi VARCHAR2(10);

--  Bảng REWARD
ALTER TABLE REWARD
ADD MoTaReward VARCHAR2(255);

-- Thêm ràng buộc khóa ngoại
--  Bảng SCHEDULE 
ALTER TABLE SCHEDULE
ADD CONSTRAINT FK_SCHEDULE_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);
ALTER TABLE SCHEDULE
ADD CONSTRAINT FK_SCHEDULE_PACKAGE FOREIGN KEY (MaGoi) REFERENCES PACKAGE(MaGoi);
ALTER TABLE SCHEDULE
ADD CONSTRAINT FK_SCHEDULE_PT FOREIGN KEY (MaPT) REFERENCES PT(MaPT);

--  Bảng PAYMENT
ALTER TABLE PAYMENT
ADD CONSTRAINT FK_PAYMENT_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);

--  Bảng REWARD
ALTER TABLE REWARD
ADD CONSTRAINT FK_REWARD_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);
ALTER TABLE REWARD
ADD CONSTRAINT FK_REWARD_DISCOUNT FOREIGN KEY (MoTaReward) REFERENCES DISCOUNT(MaGiamGia);
ALTER TABLE REWARD
ADD CONSTRAINT FK_REWARD_PROMOTION FOREIGN KEY (MoTaReward) REFERENCES PROMOTION(MaKM);
--  Bảng ATTENDANCE
ALTER TABLE ATTENDANCE
ADD CONSTRAINT FK_ATTENDANCE_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);

--  Bảng EQUIPMENT 
ALTER TABLE EQUIPMENT 
ADD CONSTRAINT FK_EQUIPMENT_WORKOUT_AREA FOREIGN KEY (MaKhuVuc) REFERENCES WORKOUT_AREA(MaKhuVuc);

--  Bảng CLASS
ALTER TABLE CLASS
ADD CONSTRAINT FK_CLASS_PT FOREIGN KEY (MaPT) REFERENCES PT(MaPT);

--  Bảng SUBSCRIPTION
ALTER TABLE SUBSCRIPTION 
ADD CONSTRAINT FK_SUBSCRIPTION_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);
ALTER TABLE SUBSCRIPTION 
ADD CONSTRAINT FK_SUBSCRIPTION_SERVICE FOREIGN KEY (MaDV) REFERENCES SERVICE(MaDV);
ALTER TABLE SUBSCRIPTION 
ADD CONSTRAINT FK_SUBSCRIPTION_PACKAGE FOREIGN KEY (MaGoi) REFERENCES PACKAGE(MaGoi);

--  Bảng MEMBERSHIP 
ALTER TABLE MEMBERSHIP 
ADD CONSTRAINT FK_MEMBERSHIP_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);

--  Bảng BOOKING
ALTER TABLE BOOKING 
ADD CONSTRAINT FK_BOOKING_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);
ALTER TABLE BOOKING 
ADD CONSTRAINT FK_BOOKING_SERVICE FOREIGN KEY (MaDV) REFERENCES SERVICE(MaDV);
ALTER TABLE BOOKING 
ADD CONSTRAINT FK_BOOKING_PACKAGE FOREIGN KEY (MaGoi) REFERENCES PACKAGE(MaGoi);

--  Bảng NOTIFICATION 
ALTER TABLE NOTIFICATION  
ADD CONSTRAINT FK_NOTIFICATION_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);

--  Bảng FEEDBACK  
ALTER TABLE FEEDBACK   
ADD CONSTRAINT FK_FEEDBACK_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);

--  Bảng MAINTENANCE   
ALTER TABLE MAINTENANCE    
ADD CONSTRAINT FK_MAINTENANCE_EQUIPMENT FOREIGN KEY (MaTB) REFERENCES EQUIPMENT(MaTB);
ALTER TABLE MAINTENANCE 
ADD CONSTRAINT FK_MAINTENANCE_STAFF FOREIGN KEY (MaNV) REFERENCES STAFF(MaNV);
--  Bảng PT_ATTENDANCE
ALTER TABLE PT_ATTENDANCE
ADD CONSTRAINT FK_PT_ATTENDANCE_PT FOREIGN KEY (MaPT) REFERENCES PT(MaPT);

--  Bảng STAFF_ATTENDANCE 
ALTER TABLE STAFF_ATTENDANCE 
ADD CONSTRAINT FK_STAFF_ATTENDANCE_STAFF FOREIGN KEY (MaNV) REFERENCES STAFF(MaNV);

--  Bảng CHALLENGE_PARTICIPATION  
ALTER TABLE CHALLENGE_PARTICIPATION  
ADD CONSTRAINT FK_CHALLENGE_PARTICIPATION_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);
ALTER TABLE CHALLENGE_PARTICIPATION  
ADD CONSTRAINT FK_CHALLENGE_PARTICIPATION_CHALLENGE FOREIGN KEY (MaChallenge) REFERENCES CHALLENGE(MaChallenge);
