--Tạo Schema
alter session set "_ORACLE_SCRIPT"=true;
CREATE USER QLYPHONGGYM IDENTIFIED BY pass123;
GRANT CONNECT, RESOURCE, DBA TO QLYPHONGGYM;


--Sử dụng Schema
ALTER SESSION SET CURRENT_SCHEMA = QLYPHONGGYM;

--Tạo bảng CUSTOMER
CREATE TABLE CUSTOMER (
  MaKH VARCHAR2(10) PRIMARY KEY,
  HoTen VARCHAR2(50) NOT NULL,
  NgaySinh DATE ,
  GioiTinh VARCHAR2(10),
  Email  VARCHAR2(50) NOT NULL,
  SoDienThoai VARCHAR2(15) NOT NULL,
  DiaChi VARCHAR2(100),
  ReferralCode VARCHAR2(20) UNIQUE
);

--Tạo bảng PACKAGE
CREATE TABLE PACKAGE (
  MaGoi VARCHAR2(10) PRIMARY KEY,
  TenGoi  VARCHAR2(50) NOT NULL,
  LoaiGoi VARCHAR2(20) CHECK (LoaiGoi IN ('Cardio', 'Gym', 'Yoga', 'Combo')),
  GiaTien NUMBER(10,2) NOT NULL,
  ThoiHan NUMBER(3) NOT NULL
);

--Tạo bảng WORKOUT_AREA
CREATE TABLE WORKOUT_AREA (
  MaKhuVuc  VARCHAR2(10) PRIMARY KEY,
  TenKhuVuc VARCHAR2(50) NOT NULL,
  SucChuaToiDa NUMBER(3) NOT NULL
); 

--Tạo bảng SCHEDULE
CREATE TABLE SCHEDULE (
  MaLich  VARCHAR2(10) PRIMARY KEY,
  MaKH  VARCHAR2(10) NOT NULL, 
  MaGoi VARCHAR2(10) NOT NULL,
  NgayTap DATE NOT NULL,
  CaTap NUMBER(1) CHECK(CaTap BETWEEN 1 AND 5),
  PhongTap VARCHAR2(20) NOT NULL, 
  MaPT VARCHAR2(10) NOT NULL
);

--Tạo bảng PT 
CREATE TABLE PT (
  MaPT  VARCHAR2(10) PRIMARY KEY,
  HoTenPT VARCHAR2(50) NOT NULL,
  ChuyenMon VARCHAR2(50),
  LichLamViec VARCHAR2(50),
  SoDienThoaiPT VARCHAR2(15) UNIQUE,
  EmailPT VARCHAR2(50) UNIQUE
);

--Tạo bảng STAFF
CREATE TABLE STAFF  (
  MaNV  VARCHAR2(10) PRIMARY KEY,
  HoTenNV VARCHAR2(50) NOT NULL,
  ViTri VARCHAR2(30) NOT NULL,
  LichLamViec VARCHAR2(50),
  SoDienThoaiNV VARCHAR2(15) UNIQUE, 
  EmailNV VARCHAR2(50) UNIQUE
);

--Tạo bảng PAYMENT
CREATE TABLE PAYMENT  (
  MaGD  VARCHAR2(15) PRIMARY KEY,
  MaKH  VARCHAR2(10) NOT NULL,
  SoTien  NUMBER(10,2) NOT NULL,
  PhuongThucTT VARCHAR2(20) CHECK(PhuongThucTT IN ('Tien Mat', 'The', 'Vi Dien Tu')),
  NgayTT DATE NOT NULL 
);

--Tạo bảng REWARD
CREATE TABLE REWARD (
  MaUuDai VARCHAR2(10)  PRIMARY KEY,
  MaKH  VARCHAR2(10)  NOT NULL,
  DiemTichLuy NUMBER(5) NOT NULL,
  MoTaUuDai VARCHAR2(100)
);

--Tạo bảng ATTENDANCE
CREATE TABLE ATTENDANCE (
  MaDiemDanh VARCHAR2(10) PRIMARY KEY,
  MaKH VARCHAR2(10) NOT NULL,
  NgayDiemDanh DATE NOT NULL,
  TrangThai VARCHAR2(20)  CHECK (TrangThai IN ('Đã điểm danh', 'Vắng mặt'))
);

--Tạo bảng EQUIPMENT
CREATE TABLE EQUIPMENT (
  MaTB  VARCHAR2(10) PRIMARY KEY,
  TenTB VARCHAR2(50) NOT NULL,
  TinhTrang VARCHAR2(20) CHECK (TinhTrang IN ('Tốt', 'Cần bảo trì', 'Hỏng')),
  MaKhuVuc  VARCHAR2(10)  NOT NULL
);

--Tạo bảng CLASS
CREATE TABLE CLASS (
  MaLop VARCHAR2(10) PRIMARY KEY,
  TenLop  VARCHAR2(50)  NOT NULL,
  MaPT  VARCHAR2(10)  NOT NULL,
  GioBatDau DATE NOT NULL,
  GioKetThuc DATE NOT NULL,
  SoLuongToiDa  NUMBER(3) NOT NULL
);

--Tạo bảng SERVICE
CREATE TABLE SERVICE (
  MaDV  VARCHAR2(10)  PRIMARY KEY,
  TenDV VARCHAR2(50)  NOT NULL,
  GiaDV NUMBER(10,2)  NOT NULL,
  MoTaDV  VARCHAR2(100)
);

--Tạo bảng SUBSCRIPTION
CREATE TABLE SUBSCRIPTION  (
  MaDK VARCHAR2(10) PRIMARY KEY,
  MaKH  VARCHAR2(10)  NOT NULL,
  MaDV  VARCHAR2(10)  NOT NULL,
  NgayDK  DATE  NOT NULL,
  TinhTrang VARCHAR2(20)  CHECK (TinhTrang IN ('Active', 'Expired'))
);

--Tạo bảng MEMBERSHIP
CREATE TABLE MEMBERSHIP (
  MaHV  VARCHAR2(10) PRIMARY KEY,
  MaKH  VARCHAR2(10) NOT NULL,
  LoaiHV  VARCHAR2(20)  CHECK (LoaiHV IN ('Silver', 'Gold', 'Platinum')),
  NgayBatDau  DATE NOT NULL,
  NgayKetThuc DATE 
);

--Tạo bảng DISCOUNT
CREATE TABLE DISCOUNT (
  MaGiamGia  VARCHAR2(10) PRIMARY KEY,
  TenMa  VARCHAR2(50) NOT NULL,
  PhanTram  NUMBER(3) CHECK (PhanTram BETWEEN 0 AND 100),
  HanSuDung DATE  NOT NULL,
  DieuKien  VARCHAR2(100)
);

--Tạo bảng BOOKING
CREATE TABLE BOOKING (
  MaBooking VARCHAR2(10) PRIMARY KEY,
  MaKH  VARCHAR2(10) NOT NULL,
  MaDV  VARCHAR2(10) NOT NULL,
  NgayDat DATE NOT NULL,
  TrangThai VARCHAR2(20)  CHECK (TrangThai IN ('Đã xác nhận', 'Chờ xử lý', 'Đã hủy'))
);

--Tạo bảng NOTIFICATION
CREATE TABLE  NOTIFICATION (
  MaTBao VARCHAR2(10) PRIMARY KEY,
  MaKH  VARCHAR2(10)  NOT NULL,
  TieuDe  VARCHAR2(50) NOT NULL,
  NoiDung VARCHAR2(255) NOT NULL,
  NgayGui DATE NOT NULL
);

--Tạo bảng FEEDBACK
CREATE TABLE FEEDBACK (
  MaFB VARCHAR2(10) PRIMARY KEY,
  MaKH VARCHAR2(10) NOT NULL,
  NoiDung VARCHAR2(255) NOT NULL,
  NgayGui DATE NOT NULL,
  DanhGia NUMBER(1) CHECK (DanhGia BETWEEN 1 AND 5)
);

--Tạo bảng MAINTENANCE
CREATE TABLE MAINTENANCE (
  MaBT  VARCHAR2(10)  PRIMARY KEY,
  MaTB  VARCHAR2(10)  NOT NULL,
  NgayBaoTri DATE NOT NULL,
  TrangThaiBT VARCHAR2(20)  CHECK (TrangThaiBT IN ('Đang xử lý', 'Hoàn thành')),
  MoTaBT  VARCHAR2(255)
);

--Tạo bảng PROMOTION
CREATE TABLE PROMOTION (
  MaKM  VARCHAR2(10)  PRIMARY KEY,
  TenKM VARCHAR2(50)  NOT NULL,
  MoTaKM  VARCHAR2(255), 
  NgayBatDau  DATE  NOT NULL,
  NgayKetThuc DATE  NOT NULL,
  PhanTramGiam  NUMBER(3) CHECK (PhanTramGiam BETWEEN 0 AND 100)
);

--Tạo bảng PT_ATTENDANCE
CREATE TABLE PT_ATTENDANCE (
  MaDDPT  VARCHAR2(10)  PRIMARY KEY,
  MaPT  VARCHAR2(10)  NOT NULL,
  NgayDiemDanh  DATE  NOT NULL,
  TrangThai VARCHAR2(20)  CHECK (TrangThai IN ('Có mặt', 'Vắng mặt', 'Nghỉ phép')),
  GhiChu  VARCHAR2(100)
);

--Tạo bảng STAFF_ATTENDANCE
CREATE TABLE STAFF_ATTENDANCE (
  MaDDNV VARCHAR2(10) PRIMARY KEY,
  MANV  VARCHAR2(10)  NOT NULL,
  NgayDiemDanh DATE NOT NULL,
  TrangThai VARCHAR2(20)  CHECK (TrangThai IN ('Có mặt', 'Vắng mặt', 'Nghỉ phép')),
  GhiChu  VARCHAR2(100)
);

--Tạo bảng CHALLENGE
CREATE TABLE CHALLENGE (
  MaChallenge VARCHAR2(10)  PRIMARY KEY,
  TenChallenge  VARCHAR2(50)  NOT NULL,
  MoTa  VARCHAR2(100) ,
  NgayBatDau  DATE  NOT NULL,
  NgayKetThuc DATE  NOT NULL,
  DiemThuong  NUMBER(5) NOT NULL
);

--Tạo bảng CHALLENGE_PARTICIPATION
CREATE TABLE CHALLENGE_PARTICIPATION (
  MaThamGia VARCHAR2(10) PRIMARY KEY,
  MaKH VARCHAR2(10) NOT NULL,
  MaChallenge VARCHAR2(10)  NOT NULL,
  TinhTrang VARCHAR2(20)  CHECK (TinhTrang IN ('Đang tham gia', 'Hoàn thành', 'Không hoàn thành')),
  NgayHoanThanh DATE
);

-- Tạo bảng SALARY
CREATE TABLE SALARY(
  MaLuong VARCHAR2(10) PRIMARY KEY,
  MaNV  VARCHAR2(10),
  MaPT  VARCHAR2(10),
  ThoiGianNhanLuong DATE NOT NULL,
  LuongCoDinh DECIMAL(12,2) NOT NULL,
  HoaHong DECIMAL(12,2) DEFAULT(0),
  Thuong  DECIMAL(12,2) DEFAULT(0),
  TruLuong  DECIMAL(12,2) DEFAULT(0),
  TongLuong DECIMAL(12,2) NOT NULL
);

-- Tạo bảng SHIFT
CREATE TABLE SHIFT(
  MaCaTap VARCHAR2(10) PRIMARY KEY,
  GioBatDau DATE NOT NULL,
  GioKetThuc DATE NOT NULL,
  MaKhuVuc VARCHAR2(10)
);
--Tạo Bảng USER
CREATE TABLE USER_ (
    USER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE,
    IS_DELETE CHAR(1) DEFAULT 'N'
);
SELECT * FROM USER_ u
ALTER TABLE USER_ DROP COLUMN PASSWORD
INSERT INTO USER_ (FULL_NAME, EMAIL)
VALUES ('Nguyễn Văn A', 'a@example.com');

INSERT INTO USER_ (FULL_NAME, EMAIL)
VALUES ('Trần Thị B', 'b@example.com');

INSERT INTO ACCOUNT (USER_ID, USERNAME, PASSWORD_HASH, STATUS)
VALUES (
    (SELECT USER_ID FROM USER_ WHERE EMAIL = 'a@example.com'),
    'nguyenvana',
    '$2a$10$9ku2CQcThZuD9Jmzl3fVXOzERZRfiut8vCEdg9KnGX0HSKX9MF9zu',
    'ACTIVE'
);
SELECT * FROM ACCOUNT a;
SELECT * FROM ACCOUNT WHERE USERNAME = 'nguyenvana';


--Tạo bảng USER_ACCOUNT
CREATE TABLE ACCOUNT (
    ACCOUNT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(200) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ACCOUNT_USER FOREIGN KEY (USER_ID) REFERENCES USER_(USER_ID)
);
ALTER TABLE ACCOUNT MODIFY USERNAME NVARCHAR2(50);




--Thêm thuộc tính
--  Bảng STAFF
ALTER TABLE STAFF
ADD Luong NUMBER(10,2) NOT NULL;
ALTER TABLE STAFF
ADD Ca VARCHAR2(10) CHECK (Ca IN ('Sáng', 'Tối'));
--  Bảng MAINTENANCE 
ALTER TABLE MAINTENANCE
ADD MaNV VARCHAR2(10);

--  Bảng SUBSCRIPTION
ALTER TABLE SUBSCRIPTION
ADD MaGoi VARCHAR2(10);
ALTER TABLE SUBSCRIPTION
ADD NgayHetHan DATE NOT NULL;

--  Bảng BOOKING
ALTER TABLE BOOKING
ADD MaGoi VARCHAR2(10);
ALTER TABLE BOOKING
ADD MaKhuVuc VARCHAR2(10);

--  Bảng REWARD
ALTER TABLE REWARD
ADD MoTaReward VARCHAR2(255);

-- Bảng SCHEDULE
ALTER TABLE SCHEDULE
ADD MaCaTap VARCHAR2(10);

-- Bảng MEMBERSHIP
ALTER TABLE MEMBERSHIP
ADD LoaiHV VARCHAR2(20) CHECK (LoaiHV IN ('Standard', 'Silver', 'Gold', 'Platinum'));
ALTER TABLE MEMBERSHIP
ADD TinhTrang VARCHAR2(20) CHECK (TinhTrang IN ('Active', 'Pause'));

-- Bảng NOTIFICATION 
ALTER TABLE NOTIFICATION
ADD SoTienHoan DECIMAL(12,2);

-- Bảng ATTENDANCE
ALTER TABLE ATTENDANCE
ADD TGDiemDanh DATE;

-- Bảng STAFF_ATTENDANCE
ALTER TABLE STAFF_ATTENDANCE
ADD TGDiemDanhStaff DATE;

-- Bảng PT_ATTENDANCE
ALTER TABLE PT_ATTENDANCE
ADD TGDiemDanhPT DATE;

-- Bảng PAYMENT
ALTER TABLE PAYMENT
ADD MaGoi VARCHAR2(20);

-- Xóa thuộc tính
-- Bảng SCHEDULE
ALTER TABLE SCHEDULE DROP COLUMN CaTap;
ALTER TABLE SCHEDULE DROP COLUMN PhongTap;
-- Bảng PT
ALTER TABLE PT DROP COLUMN LichLamViec;
--Bảng CLASS
ALTER TABLE CLASS DROP COLUMN GioBatDau;
ALTER TABLE CLASS DROP COLUMN GioKetThuc;
-- Bảng MEMBERSHIP
ALTER TABLE MEMBERSHIP DROP COLUMN LoaiHV; 
-- Bảng PROMOTION 
ALTER TABLE PROMOTION DROP COLUMN PhanTramGiam;
-- Bảng ATTENDANCE
ALTER TABLE ATTENDANCE DROP COLUMN TGDiemdanh;
-- Bảng PT_ATTENDANCE
ALTER TABLE PT_ATTENDANCE DROP COLUMN TGDiemdanhPT;
-- Bảng STAFF_ATTENDANCE
ALTER TABLE STAFF_ATTENDANCE DROP COLUMN TGDiemdanhStaff;

-- Sửa thuộc tính
-- Bảng PROMOTION 
ALTER TABLE PROMOTION 
MODIFY MoTaKM SMALLINT;
-- Bảng MEMBERSHIP
ALTER TABLE MEMBERSHIP
MODIFY LoaiHV CHECK (LoaiHV IN ('Standard', 'VIP'));
-- Bảng SUBSCRIPTION
ALTER TABLE SUBSCRIPTION
MODIFY MaGoi NOT NULL;
-- Bảng NOTIFICATION
ALTER TABLE NOTIFICATION
MODIFY MaTBao VARCHAR2(30);
-- Thêm ràng buộc khóa ngoại
--  Bảng SCHEDULE 
ALTER TABLE SCHEDULE
ADD CONSTRAINT FK_SCHEDULE_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);
ALTER TABLE SCHEDULE
ADD CONSTRAINT FK_SCHEDULE_PACKAGE FOREIGN KEY (MaGoi) REFERENCES PACKAGE(MaGoi);
ALTER TABLE SCHEDULE
ADD CONSTRAINT FK_SCHEDULE_PT FOREIGN KEY (MaPT) REFERENCES PT(MaPT);
ALTER TABLE SCHEDULE
ADD CONSTRAINT FK_SCHEDULE_SHIFT FOREIGN KEY (MaCaTap) REFERENCES SHIFT(MaCaTap);

--  Bảng PAYMENT
ALTER TABLE PAYMENT
ADD CONSTRAINT FK_PAYMENT_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);
ALTER TABLE PAYMENT
ADD CONSTRAINT FK_PAYMENT_PACKAGE FOREIGN KEY (MaGoi) REFERENCES PACKAGE(MaGoi);
--  Bảng REWARD
ALTER TABLE REWARD
ADD CONSTRAINT FK_REWARD_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);
ALTER TABLE REWARD
ADD CONSTRAINT FK_REWARD_DISCOUNT FOREIGN KEY (MoTaReward) REFERENCES DISCOUNT(MaGiamGia);
ALTER TABLE REWARD
ADD CONSTRAINT FK_REWARD_PROMOTION FOREIGN KEY (MoTaReward) REFERENCES PROMOTION(MaKM);
--  Bảng ATTENDANCE
ALTER TABLE ATTENDANCE
ADD CONSTRAINT FK_ATTENDANCE_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);

--  Bảng EQUIPMENT 
ALTER TABLE EQUIPMENT 
ADD CONSTRAINT FK_EQUIPMENT_WORKOUT_AREA FOREIGN KEY (MaKhuVuc) REFERENCES WORKOUT_AREA(MaKhuVuc);

--  Bảng CLASS
ALTER TABLE CLASS
ADD CONSTRAINT FK_CLASS_PT FOREIGN KEY (MaPT) REFERENCES PT(MaPT);

--  Bảng SUBSCRIPTION
ALTER TABLE SUBSCRIPTION 
ADD CONSTRAINT FK_SUBSCRIPTION_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);
ALTER TABLE SUBSCRIPTION 
ADD CONSTRAINT FK_SUBSCRIPTION_SERVICE FOREIGN KEY (MaDV) REFERENCES SERVICE(MaDV);
ALTER TABLE SUBSCRIPTION 
ADD CONSTRAINT FK_SUBSCRIPTION_PACKAGE FOREIGN KEY (MaGoi) REFERENCES PACKAGE(MaGoi);

--  Bảng MEMBERSHIP 
ALTER TABLE MEMBERSHIP 
ADD CONSTRAINT FK_MEMBERSHIP_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);

--  Bảng BOOKING
ALTER TABLE BOOKING 
ADD CONSTRAINT FK_BOOKING_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);
ALTER TABLE BOOKING 
ADD CONSTRAINT FK_BOOKING_SERVICE FOREIGN KEY (MaDV) REFERENCES SERVICE(MaDV);
ALTER TABLE BOOKING 
ADD CONSTRAINT FK_BOOKING_PACKAGE FOREIGN KEY (MaGoi) REFERENCES PACKAGE(MaGoi);
ALTER TABLE BOOKING 
ADD CONSTRAINT FK_BOOKING_WORKOUT_AREA FOREIGN KEY (MaKhuVuc) REFERENCES WORKOUT_AREA(MaKhuVuc);

--  Bảng NOTIFICATION 
ALTER TABLE NOTIFICATION  
ADD CONSTRAINT FK_NOTIFICATION_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);

--  Bảng FEEDBACK  
ALTER TABLE FEEDBACK   
ADD CONSTRAINT FK_FEEDBACK_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);

--  Bảng MAINTENANCE   
ALTER TABLE MAINTENANCE    
ADD CONSTRAINT FK_MAINTENANCE_EQUIPMENT FOREIGN KEY (MaTB) REFERENCES EQUIPMENT(MaTB);
ALTER TABLE MAINTENANCE 
ADD CONSTRAINT FK_MAINTENANCE_STAFF FOREIGN KEY (MaNV) REFERENCES STAFF(MaNV);
--  Bảng PT_ATTENDANCE
ALTER TABLE PT_ATTENDANCE
ADD CONSTRAINT FK_PT_ATTENDANCE_PT FOREIGN KEY (MaPT) REFERENCES PT(MaPT);

--  Bảng STAFF_ATTENDANCE 
ALTER TABLE STAFF_ATTENDANCE 
ADD CONSTRAINT FK_STAFF_ATTENDANCE_STAFF FOREIGN KEY (MaNV) REFERENCES STAFF(MaNV);

--  Bảng CHALLENGE_PARTICIPATION  
ALTER TABLE CHALLENGE_PARTICIPATION  
ADD CONSTRAINT FK_CHALLENGE_PARTICIPATION_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH);
ALTER TABLE CHALLENGE_PARTICIPATION  
ADD CONSTRAINT FK_CHALLENGE_PARTICIPATION_CHALLENGE FOREIGN KEY (MaChallenge) REFERENCES CHALLENGE(MaChallenge);

-- Bảng SALARY
ALTER TABLE SALARY
ADD CONSTRAINT FK_SALARY_STAFF FOREIGN KEY (MaNV) REFERENCES STAFF(MaNV);
ALTER TABLE SALARY
ADD CONSTRAINT FK_PT_SALARY_PT FOREIGN KEY (MaPT) REFERENCES PT(MaPT);
-- Bảng SHIFT
ALTER TABLE SHIFT
ADD CONSTRAINT FK_SHIFT_WORKOUT_AREA FOREIGN KEY (MaKhuVuc) REFERENCES WORKOUT_AREA(MaKhuVuc);



-- Function
-- Đếm gói tập đã dki của khách hàng
DROP FUNCTION CountSubPackage

CREATE OR REPLACE FUNCTION CountSubPackage(p_MaKH VARCHAR2)
RETURN NUMBER
IS
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO v_count
  FROM SUBSCRIPTION s
  WHERE s.MaKH = p_MaKH;
  
  RETURN v_count;
END;
/
SELECT * FROM SERVICE s;
SELECT * FROM SUBSCRIPTION s;
SELECT * FROM PACKAGE p;
SELECT * FROM BOOKING b;
SELECT * FROM SCHEDULE s;
SELECT * FROM ATTENDANCE a;
/
-- Kiểm tra thông tin gói tập
DROP FUNCTION BookPackage

CREATE OR REPLACE FUNCTION BookPackage(p_MaGoi VARCHAR2)
RETURN VARCHAR2
IS
  v_info VARCHAR2(200);
BEGIN
  SELECT 'Gói: ' || P.TENGOI || ', Giá: ' || TO_CHAR(P.GIATIEN) || ', Thời hạn: ' || TO_CHAR(P.THOIHAN) || ' tháng' 
  INTO V_INFO
  FROM PACKAGE p
  WHERE P.MAGOI  = P_MAGOI;
  RETURN V_INFO;
  EXCEPTION WHEN NO_DATA_FOUND THEN
  RETURN 'Không tìm thấy gói tập';
END;

--Đếm số lịch tập của khách hàng vào 1 ngày cụ thể
DROP FUNCTION GetCustomerSchedule

CREATE OR REPLACE FUNCTION CountCustomerSchedule(p_MaKH VARCHAR2, p_Ngay DATE)
RETURN NUMBER
IS
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO v_count
  FROM SCHEDULE
  WHERE MaKH = p_MaKH
    AND NgayTap = p_Ngay;
  
  RETURN v_count;
END;
/


-- Lấy hồ sơ khách hàng
DROP FUNCTION GetCustomerProfile

CREATE OR REPLACE FUNCTION GetCustomerProfile(p_maKH VARCHAR2)
RETURN VARCHAR2
IS
  v_profile VARCHAR2(200);
BEGIN
    SELECT 'Họ tên: '||HoTen ||', Ngày sinh: '|| TO_CHAR(NgaySinh)||'. Giới tính: ' || GioiTinh ||', Email:  '|| Email
    ||', Số điện thoại: '||SoDienThoai||', Địa chỉ'|| DiaChi
    INTO v_profile
    FROM CUSTOMER
    WHERE MaKH = p_maKH;
  RETURN v_profile;
END;
/

--Kiểm tra điểm tích lũy
DROP FUNCTION GetCustomerPoint

CREATE OR REPLACE FUNCTION GetCustomerPoint (p_KhachHang VARCHAR2)
RETURN NUMBER
IS
  v_point NUMBER;
BEGIN
  SELECT NVL(SUM(R.DIEMTICHLUY),0)
  INTO V_POINT
  FROM REWARD r
  WHERE r.MAKH = P_KHACHHANG;
  RETURN V_POINT;
END;

-- Đếm số lượng pt hiện có
CREATE OR REPLACE FUNCTION GetTotalPT
RETURN NUMBER
IS
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO v_count
  FROM PT;
  
  RETURN v_count;
END;
/

--Tính phần trăm số buổi tập khách tham gia so với tổng buổi tập có lịch
CREATE OR REPLACE FUNCTION GetAttendancePercentage(p_maKH VARCHAR2)
RETURN NUMBER
IS
  v_attended NUMBER;
  v_total NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_attended
  FROM ATTENDANCE
  WHERE MaKH = p_maKH AND TrangThai = 'Đã điểm danh';
  
  SELECT COUNT(*) INTO v_total
  FROM SCHEDULE
  WHERE MaKH = p_maKH;
  
  IF v_total = 0 THEN
    RETURN 0;
  ELSE
    RETURN ROUND((v_attended / v_total) * 100, 2);
  END IF;
END;
/

--Top khách hàng có số buổi tập cao nhất
DROP FUNCTION GetTopCustomerAttendance
CREATE OR REPLACE FUNCTION GetTopCustomerAttendance
RETURN VARCHAR2
IS
  v_topCustomer VARCHAR2(50);
BEGIN
  SELECT HoTen
  INTO v_topCustomer
  FROM (
  SELECT C.HOTEN, COUNT(A.MADIEMDANH) AS Attendance_count
  FROM CUSTOMER c
  JOIN ATTENDANCE a ON c.MaKH = a.MaKH
  WHERE a.TrangThai = 'Đã điểm danh'
  GROUP BY c.HoTen
  ORDER BY COUNT(a.MaDiemDanh) DESC
  )
  WHERE ROWNUM = 1;
  
  RETURN v_topCustomer;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 'Không có dữ liệu';
END;
/

--Tính tổng doanh thu từ khách hàng VIP
CREATE OR REPLACE FUNCTION GetRevenueFromVIP
RETURN NUMBER
IS
  v_total NUMBER;
BEGIN
  SELECT NVL(SUM(p.SoTien), 0)
  INTO v_total
  FROM PAYMENT p
  JOIN MEMBERSHIP m ON p.MaKH = m.MaKH
  WHERE m.LoaiHV = 'VIP';
  
  RETURN v_total;
END;
/

--Procedure
--Hiển thị danh sách gói tập của khách hàng
CREATE OR REPLACE PROCEDURE ShowCustomerPackages(
  p_maKH IN VARCHAR2,
  p_cursor OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN p_cursor FOR
    SELECT p.MaGoi, p.TenGoi, p.LoaiGoi, p.GiaTien, p.ThoiHan, s.NgayDK, s.TinhTrang
    FROM SUBSCRIPTION s
    JOIN PACKAGE p ON s.MaGoi = p.MaGoi
    WHERE s.MaKH = p_maKH;
END;
/

--Hiển thị lịch tập của khách hàng trong 1 tháng
CREATE OR REPLACE PROCEDURE ShowScheduleByCustomer(
  p_maKH IN VARCHAR2,
  p_month IN NUMBER,
  p_cursor OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN p_cursor FOR
    SELECT s.MaLich, s.NgayTap, s.MaCaTap, pt.HoTenPT
    FROM SCHEDULE s
    JOIN PT pt ON s.MaPT = pt.MaPT
    WHERE s.MaKH = p_maKH
     AND EXTRACT(MONTH FROM s.NgayTap) = p_month;
END;
/
SELECT * FROM SCHEDULE s


--Hiển thị danh sách khách hàng sắp hết hạn gói tập
CREATE OR REPLACE PROCEDURE ShowExpiringSubscriptions(
  p_days IN NUMBER,
  p_cursor OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN p_cursor FOR
    SELECT MaDK, MaKH, MaGoi, NgayHetHan
    FROM SUBSCRIPTION
    WHERE NgayHetHan BETWEEN SYSDATE AND (SYSDATE + p_days);
END;

SELECT * FROM SUBSCRIPTION s
--Sửa thông tin gói tập
CREATE OR REPLACE PROCEDURE UpdatePackageInfo(
  p_maGoi IN VARCHAR2,
  p_tenGoi IN VARCHAR2,
  p_loaiGoi IN VARCHAR2,
  p_giaTien IN NUMBER,
  p_thoiHan IN NUMBER
)
IS
BEGIN
  UPDATE PACKAGE
  SET TenGoi = p_tenGoi,
      LoaiGoi = p_loaiGoi,
      GiaTien = p_giaTien,
      ThoiHan = p_thoiHan
  WHERE MaGoi = p_maGoi;
  
  IF SQL%ROWCOUNT = 0 THEN
    DBMS_OUTPUT.PUT_LINE('Không tìm thấy gói tập có mã: ' || p_maGoi);
  ELSE
    DBMS_OUTPUT.PUT_LINE('Đã cập nhật gói tập: ' || p_maGoi);
  END IF;
  
  COMMIT;
END;
/
