--Tạo Schema
alter session set "_ORACLE_SCRIPT"=true;
CREATE USER QLYPHONGGYM IDENTIFIED BY pass123;
GRANT CONNECT, RESOURCE, DBA TO QLYPHONGGYM;


--Sử dụng Schema
ALTER SESSION SET CURRENT_SCHEMA = QLYPHONGGYM;

-- Bảng CUSTOMER
CREATE TABLE CUSTOMER (
    MaKH VARCHAR2(10) PRIMARY KEY,
    TenKH VARCHAR2(100),
    Email VARCHAR2(100),
    SDT VARCHAR2(15),
    DiaChi VARCHAR2(255),
    NgaySinh DATE
);

-- Bảng PACKAGE
CREATE TABLE PACKAGE (
    MaGoi VARCHAR2(10) PRIMARY KEY,
    TenGoi VARCHAR2(100),
    ThoiHan NUMBER,
    Gia NUMBER(10, 2)
);

-- Bảng WORKOUT_AREA
CREATE TABLE WORKOUT_AREA (
    MaKhuVuc VARCHAR2(10) PRIMARY KEY,
    TenKhuVuc VARCHAR2(100)
);

-- Bảng SHIFT
CREATE TABLE SHIFT (
    MaCaTap VARCHAR2(10) PRIMARY KEY,
    TenCaTap VARCHAR2(100),
    ThoiGianBatDau DATE,
    ThoiGianKetThuc DATE,
    MaKhuVuc VARCHAR2(10),
    CONSTRAINT FK_SHIFT_WORKOUT_AREA FOREIGN KEY (MaKhuVuc) REFERENCES WORKOUT_AREA(MaKhuVuc)
);

-- Bảng PT
CREATE TABLE PT (
    MaPT VARCHAR2(10) PRIMARY KEY,
    TenPT VARCHAR2(100),
    Email VARCHAR2(100),
    SDT VARCHAR2(15)
);

-- Bảng STAFF
CREATE TABLE STAFF (
    MaNV VARCHAR2(10) PRIMARY KEY,
    TenNV VARCHAR2(100),
    Email VARCHAR2(100),
    SDT VARCHAR2(15),
    Luong NUMBER(10,2) NOT NULL,
    Ca VARCHAR2(10) CHECK (Ca IN ('Sáng', 'Tối'))
);

-- Bảng SCHEDULE
CREATE TABLE SCHEDULE (
    MaLich VARCHAR2(10) PRIMARY KEY,
    MaKH VARCHAR2(10),
    MaPT VARCHAR2(10),
    MaGoi VARCHAR2(10),
    MaCaTap VARCHAR2(10),
    CONSTRAINT FK_SCHEDULE_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH),
    CONSTRAINT FK_SCHEDULE_PT FOREIGN KEY (MaPT) REFERENCES PT(MaPT),
    CONSTRAINT FK_SCHEDULE_PACKAGE FOREIGN KEY (MaGoi) REFERENCES PACKAGE(MaGoi),
    CONSTRAINT FK_SCHEDULE_SHIFT FOREIGN KEY (MaCaTap) REFERENCES SHIFT(MaCaTap)
);

-- Bảng EQUIPMENT
CREATE TABLE EQUIPMENT (
    MaTB VARCHAR2(10) PRIMARY KEY,
    TenTB VARCHAR2(100),
    MaKhuVuc VARCHAR2(10),
    CONSTRAINT FK_EQUIPMENT_WORKOUT_AREA FOREIGN KEY (MaKhuVuc) REFERENCES WORKOUT_AREA(MaKhuVuc)
);

-- Bảng CLASS
CREATE TABLE CLASS (
    MaLop VARCHAR2(10) PRIMARY KEY,
    TenLop VARCHAR2(100),
    MaPT VARCHAR2(10),
    CONSTRAINT FK_CLASS_PT FOREIGN KEY (MaPT) REFERENCES PT(MaPT)
);

-- Bảng SERVICE
CREATE TABLE SERVICE (
    MaDV VARCHAR2(10) PRIMARY KEY,
    TenDV VARCHAR2(100),
    GiaDV NUMBER(10,2)
);

-- Bảng SUBSCRIPTION
CREATE TABLE SUBSCRIPTION (
    MaDK VARCHAR2(10) PRIMARY KEY,
    MaKH VARCHAR2(10),
    MaDV VARCHAR2(10),
    MaGoi VARCHAR2(10) NOT NULL,
    NgayHetHan DATE NOT NULL,
    CONSTRAINT FK_SUBSCRIPTION_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH),
    CONSTRAINT FK_SUBSCRIPTION_SERVICE FOREIGN KEY (MaDV) REFERENCES SERVICE(MaDV),
    CONSTRAINT FK_SUBSCRIPTION_PACKAGE FOREIGN KEY (MaGoi) REFERENCES PACKAGE(MaGoi)
);

-- Bảng MEMBERSHIP
CREATE TABLE MEMBERSHIP (
    MaHV VARCHAR2(10) PRIMARY KEY,
    MaKH VARCHAR2(10),
    LoaiHV VARCHAR2(20) CHECK (LoaiHV IN ('Standard', 'VIP')),
    TinhTrang VARCHAR2(20) CHECK (TinhTrang IN ('Active', 'Pause')),
    CONSTRAINT FK_MEMBERSHIP_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH)
);

-- Bảng DISCOUNT
CREATE TABLE DISCOUNT (
    MaGiamGia VARCHAR2(10) PRIMARY KEY,
    GiaTriGiam NUMBER(10,2)
);

-- Bảng PROMOTION
CREATE TABLE PROMOTION (
    MaKM VARCHAR2(10) PRIMARY KEY,
    MoTaKM SMALLINT
);

-- Bảng BOOKING
CREATE TABLE BOOKING (
    MaBooking VARCHAR2(10) PRIMARY KEY,
    MaKH VARCHAR2(10),
    MaDV VARCHAR2(10),
    MaGoi VARCHAR2(10),
    MaKhuVuc VARCHAR2(10),
    CONSTRAINT FK_BOOKING_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH),
    CONSTRAINT FK_BOOKING_SERVICE FOREIGN KEY (MaDV) REFERENCES SERVICE(MaDV),
    CONSTRAINT FK_BOOKING_PACKAGE FOREIGN KEY (MaGoi) REFERENCES PACKAGE(MaGoi),
    CONSTRAINT FK_BOOKING_WORKOUT_AREA FOREIGN KEY (MaKhuVuc) REFERENCES WORKOUT_AREA(MaKhuVuc)
);

-- Bảng NOTIFICATION
CREATE TABLE NOTIFICATION (
    MaTBao VARCHAR2(30) PRIMARY KEY,
    MaKH VARCHAR2(10),
    NoiDung VARCHAR2(255),
    SoTienHoan DECIMAL(12,2),
    CONSTRAINT FK_NOTIFICATION_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH)
);

-- Bảng FEEDBACK
CREATE TABLE FEEDBACK (
    MaFB VARCHAR2(10) PRIMARY KEY,
    MaKH VARCHAR2(10),
    NoiDung VARCHAR2(255),
    CONSTRAINT FK_FEEDBACK_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH)
);

-- Bảng REWARD
CREATE TABLE REWARD (
    MaReward VARCHAR2(10) PRIMARY KEY,
    MaKH VARCHAR2(10),
    MoTaReward VARCHAR2(255),
    CONSTRAINT FK_REWARD_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH),
    CONSTRAINT FK_REWARD_DISCOUNT FOREIGN KEY (MoTaReward) REFERENCES DISCOUNT(MaGiamGia),
    CONSTRAINT FK_REWARD_PROMOTION FOREIGN KEY (MoTaReward) REFERENCES PROMOTION(MaKM)
);

-- Bảng MAINTENANCE
CREATE TABLE MAINTENANCE (
    MaSC VARCHAR2(10) PRIMARY KEY,
    MaTB VARCHAR2(10),
    MaNV VARCHAR2(10),
    MoTaSC VARCHAR2(255),
    CONSTRAINT FK_MAINTENANCE_EQUIPMENT FOREIGN KEY (MaTB) REFERENCES EQUIPMENT(MaTB),
    CONSTRAINT FK_MAINTENANCE_STAFF FOREIGN KEY (MaNV) REFERENCES STAFF(MaNV)
);

-- Bảng ATTENDANCE
CREATE TABLE ATTENDANCE (
    MaDD VARCHAR2(10) PRIMARY KEY,
    MaKH VARCHAR2(10),
    CONSTRAINT FK_ATTENDANCE_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH)
);

-- Bảng PT_ATTENDANCE
CREATE TABLE PT_ATTENDANCE (
    MaDDPT VARCHAR2(10) PRIMARY KEY,
    MaPT VARCHAR2(10),
    CONSTRAINT FK_PT_ATTENDANCE_PT FOREIGN KEY (MaPT) REFERENCES PT(MaPT)
);

-- Bảng STAFF_ATTENDANCE
CREATE TABLE STAFF_ATTENDANCE (
    MaDDStaff VARCHAR2(10) PRIMARY KEY,
    MaNV VARCHAR2(10),
    CONSTRAINT FK_STAFF_ATTENDANCE_STAFF FOREIGN KEY (MaNV) REFERENCES STAFF(MaNV)
);

-- Bảng CHALLENGE
CREATE TABLE CHALLENGE (
    MaChallenge VARCHAR2(10) PRIMARY KEY,
    TenChallenge VARCHAR2(100),
    MoTaChallenge VARCHAR2(255)
);

-- Bảng CHALLENGE_PARTICIPATION
CREATE TABLE CHALLENGE_PARTICIPATION (
    MaThamGia VARCHAR2(10) PRIMARY KEY,
    MaKH VARCHAR2(10),
    MaChallenge VARCHAR2(10),
    CONSTRAINT FK_CHALLENGE_PARTICIPATION_CUSTOMER FOREIGN KEY (MaKH) REFERENCES CUSTOMER(MaKH),
    CONSTRAINT FK_CHALLENGE_PARTICIPATION_CHALLENGE FOREIGN KEY (MaChallenge) REFERENCES CHALLENGE(MaChallenge)
);

-- Bảng SALARY
CREATE TABLE SALARY (
    MaLuong VARCHAR2(10) PRIMARY KEY,
    MaNV VARCHAR2(10),
    MaPT VARCHAR2(10),
    LuongThang NUMBER(10,2),
    CONSTRAINT FK_SALARY_STAFF FOREIGN KEY (MaNV) REFERENCES STAFF(MaNV),
    CONSTRAINT FK_PT_SALARY_PT FOREIGN KEY (MaPT) REFERENCES PT(MaPT)
);

--------------------------------------------------------------Các Bảng Dùng Cho Login Và Phân Quyền----------------------------------------------------------------------------------------------

-- 1. Tạo bảng USER
CREATE TABLE USER (
    USER_ID      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FULL_NAME    VARCHAR2(100) NOT NULL,
    EMAIL        VARCHAR2(150) UNIQUE NOT NULL,
    CREATED_AT   DATE DEFAULT SYSDATE,
    UPDATED_AT   DATE DEFAULT SYSDATE,
    IS_DELETED   NUMBER(1) DEFAULT 0 CHECK (IS_DELETED IN (0,1))
);

-- 2. Tạo bảng ACCOUNT
CREATE TABLE ACCOUNT (
    ACCOUNT_ID    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID       NUMBER(10) NOT NULL,
    USERNAME      VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(200) NOT NULL,
    STATUS        VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_AT    DATE DEFAULT SYSDATE,
    UPDATED_AT    DATE DEFAULT SYSDATE,
    IS_DELETED    NUMBER(1) DEFAULT 0 CHECK (IS_DELETED IN (0,1)),
    CONSTRAINT FK_ACCOUNT_USER FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID)
);

-- 3. Tạo bảng FUNCTION
CREATE TABLE FUNCTION (
    FUNCTION_ID   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME_FUNCTION VARCHAR2(100) NOT NULL,
    CREATED_AT    DATE DEFAULT SYSDATE,
    UPDATED_AT    DATE DEFAULT SYSDATE,
    IS_DELETED    NUMBER(1) DEFAULT 0 CHECK (IS_DELETED IN (0,1))
);

-- 4. Tạo bảng ROLE
CREATE TABLE ROLE (
    ROLE_ID     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FUNCTION_ID NUMBER(10) NOT NULL,
    ADD_PERM    NUMBER(1) DEFAULT 0 CHECK (ADD_PERM IN (0,1)),
    EDIT_PERM   NUMBER(1) DEFAULT 0 CHECK (EDIT_PERM IN (0,1)),
    DELETE_PERM NUMBER(1) DEFAULT 0 CHECK (DELETE_PERM IN (0,1)),
    DOWNLOAD_PERM NUMBER(1) DEFAULT 0 CHECK (DOWNLOAD_PERM IN (0,1)),
    VIEW_PERM   NUMBER(1) DEFAULT 0 CHECK (VIEW_PERM IN (0,1)),
    CREATED_AT  DATE DEFAULT SYSDATE,
    UPDATED_AT  DATE DEFAULT SYSDATE,
    IS_DELETED  NUMBER(1) DEFAULT 0 CHECK (IS_DELETED IN (0,1)),
    CONSTRAINT FK_ROLE_FUNCTION FOREIGN KEY (FUNCTION_ID) REFERENCES FUNCTION(FUNCTION_ID)
);

-- 5. Tạo bảng ROLE_GROUP
CREATE TABLE ROLE_GROUP (
    ROLE_GROUP_ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME_ROLE_GROUP VARCHAR2(100) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE DEFAULT SYSDATE,
    IS_DELETED NUMBER(1) DEFAULT 0 CHECK (IS_DELETED IN (0,1))
);

-- 6. Tạo bảng ROLE_GROUP_ASSIGN_ROLE
CREATE TABLE ROLE_GROUP_ASSIGN_ROLE (
    ROLE_GROUP_ID NUMBER(10) NOT NULL,
    ROLE_ID       NUMBER(10) NOT NULL,
    CREATED_AT    DATE DEFAULT SYSDATE,
    UPDATED_AT    DATE DEFAULT SYSDATE,
    IS_DELETED    NUMBER(1) DEFAULT 0 CHECK (IS_DELETED IN (0,1)),
    CONSTRAINT PK_ROLE_GROUP_ASSIGN_ROLE PRIMARY KEY (ROLE_GROUP_ID, ROLE_ID),
    CONSTRAINT FK_ROLE_GROUP FOREIGN KEY (ROLE_GROUP_ID) REFERENCES ROLE_GROUP(ROLE_GROUP_ID),
    CONSTRAINT FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
);

-- 7. Tạo bảng ACCOUNT_ASSIGN_ROLE_GROUP
CREATE TABLE ACCOUNT_ASSIGN_ROLE_GROUP (
    ACCOUNT_ID    NUMBER(10) NOT NULL,
    ROLE_GROUP_ID NUMBER(10) NOT NULL,
    CREATED_AT    DATE DEFAULT SYSDATE,
    UPDATED_AT    DATE DEFAULT SYSDATE,
    IS_DELETED    NUMBER(1) DEFAULT 0 CHECK (IS_DELETED IN (0,1)),
    CONSTRAINT PK_ACCOUNT_ASSIGN_ROLE_GROUP PRIMARY KEY (ACCOUNT_ID, ROLE_GROUP_ID),
    CONSTRAINT FK_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID),
    CONSTRAINT FK_ROLE_GROUP_ASSIGN FOREIGN KEY (ROLE_GROUP_ID) REFERENCES ROLE_GROUP(ROLE_GROUP_ID)
);

-- 8. Tạo bảng ACCOUNT_ASSIGN_ROLE
CREATE TABLE ACCOUNT_ASSIGN_ROLE (
    ACCOUNT_ID  NUMBER(10) NOT NULL,
    ROLE_ID     NUMBER(10) NOT NULL,
    CREATED_AT  DATE DEFAULT SYSDATE,
    UPDATED_AT  DATE DEFAULT SYSDATE,
    IS_DELETED  NUMBER(1) DEFAULT 0 CHECK (IS_DELETED IN (0,1)),
    CONSTRAINT PK_ACCOUNT_ASSIGN_ROLE PRIMARY KEY (ACCOUNT_ID, ROLE_ID),
    CONSTRAINT FK_ACCOUNT_ROLE FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID),
    CONSTRAINT FK_ROLE_ASSIGN FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
);

-- 9. Tạo bảng ACCOUNT_TOKEN
CREATE TABLE ACCOUNT_TOKEN (
    TOKEN_ID      NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ACCOUNT_ID    NUMBER(10) NOT NULL,
    TOKEN_VALUE   VARCHAR2(500) UNIQUE NOT NULL,
    EXPIRES_AT    DATE NOT NULL,
    ISSUED_AT     DATE DEFAULT SYSDATE,
    IS_REVOKED    CHAR(1) DEFAULT 'N' CHECK (IS_REVOKED IN ('Y', 'N')),
    CONSTRAINT FK_TOKEN_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

